<template>
  <div>
    <div id="header-bg" class="select-none max-w-5xl mx-auto h-32 sm:h-56 object-cover bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500 text-white text-4xl sm:text-5xl font-semibold pl-10 flex items-center">
      ORDER DISPATCH SYSTEM
    </div>
    <div class="flex flex-col sm:flex-row mx-auto my-5 max-w-5xl relative">
      <div id="summary" class="flex-shrink-0 border-b-2 mx-5 sm:mx-0 sm:border-b-0 sm:border-r-2 border-gray-300 pr-10 pl-5 sm:pl-10 pb-5 sm:py-5">
        <h3>
          Case Study
        </h3>
        <p>Order Dispatch System</p>
        <p>KiwiQuads, Auckland</p>
        <h3>
          Type
        </h3>
        <p>Ecommerce Web Tool</p>
        <h3>
          Tools used
        </h3>
        <p>Nuxt JS</p>
        <p>Vue</p>
        <p>Visual Studio C#</p>
        <p>PDFSharp .NET</p>
      </div>
      <article id="content" class="px-10 pb-5">
        <h3>
          Goal
        </h3>
        <p>
          To build a web app which makes the order packing process for KiwiQuads efficient, simple, and functional.
        </p>
        <h3>
          What does an order dispatch system do?
        </h3>
        <p>
          This project used a JAMstack architecture to combine the WooCommerce Orders API, NZPost Shipping API, and a local invoice generator app to simplify the process of packing orders, generating shipping labels, and printing invoices. The system is accessible at any location and secured using access keys.
        </p>
        <img class="block w-full h-auto py-5" src="~/static/images/dispatch-full.jpg">
        <p style="font-size:1rem" class="text-center mb-5 italic">
          The dispatch app is split into 3 sections for each part of the shipping process
        </p>
        <h3>
          The Problem
        </h3>
        <p>
          As KiwiQuads continued to grow and ship more orders each day, we needed to simplify the packing process into an efficient system which could be easily taught to new staff members. The previous system was prone to picking errors, and took much longer than needed to ship each order as three different systems needed to be used to print each order. My primary goal was to eliminate picking error and reduce packing time. My secondary goal was to create an easier way to generate invoices.
          <br><br>
        </p>
        <h3>
          My Solution
        </h3>
        <p>
          I opted to build this tool as a web app so that it could be accessible by any staff when required. I began by mapping out the inputs, outputs, and functions that app needed on paper. Once I understood the flow of the page, I drafted some UI concepts in Figma and began a new Nuxt/Vue project. <br><br>Once the first prototype was finished, I presented it to our picking team whom provided valuable feedback on the flow and layout of the application. After the web app had been through several revisions, the picking team began to use it as part of their daily workflow. I then started work on my secondary goal of building a invoice generation tool.<br><br>As the invoices only needed to be generated on one machine for printing, I decided to build this tool in Visual Studio .NET which had much better libraries for generating documents, PDFs, and automated printing. I wanted the whole process to be a one button click for the packer so that no additional dialogs would appear.
        </p>
        <img class="w-80 mx-auto h-auto py-5 px-5 inline-block" src="~/static/images/invoice-generator.jpg">
        <img class="w-80 mx-auto h-auto py-5 px-5 inline-block shadow-md" src="~/static/images/invoice.jpg">
        <p style="font-size:1rem" class="text-center my-5 italic">
          The backend invoice generator and an invoice generated by it
        </p>
        <p>
          The application opens a local websocket which accepts JSON data. Orders can be sent to the tool from the Dispatch web app via the websocket. The tool then generates the invoice, prints it, and logs the event. I later added support for printing various labels depending if the customer wanted to pickup their order locally.
        </p>
        <h3>
          Challenges
        </h3>
        <p>
          This was the biggest web app I have worked on so far. It really tested my skills in working with a complex project. There are many supporting functions which manipulate the data between the two integrations. My biggest challenge was finding a way to efficiently store the large amount of data from the WooCommerce API then building the communication between the web app and the invoice generation tool. I thought the websocket was a really elegant solution to this and works incredibly well.
        </p>
        <h3>
          Conclusion
        </h3>
        <p>
          This was one of the best tools I have built for KiwiQuads. It saves many hours of time every week and has eliminated picking error almost completely. I am proud to say I achieved both my two goals of reducing picking error and automating the invoice generation process. Since the project was completed, I have continued to add additional functionality such as built-in barcode scanning, and 2D barcodes printed on the invoices for integration with future warehouse systems we may use.
        </p>
      </article>
    </div>
  </div>
</template>

<script>

export default {
  layout: 'project',
  head () {
    return {
      title: 'Oliver Noles - 3D Drone Customiser Project',
      description: 'Oliver Noles Portfolio. 3D Drone Customiser Project'
    }
  }
}
</script>

<style scoped>
#header-bg {
  background-image:
    linear-gradient(to bottom, rgba(0, 0, 0, 0.768), rgba(126, 126, 126, 0.494)),
    url(~/assets/dispatch-1.jpg);
  background-size: 100%;
  background-position: center;
  background-repeat: no-repeat;
}
#content p, #summary p {
    font-size: 1.25rem/* 20px */;
    line-height: 1.75rem/* 28px */;
}
#content h3, #summary h3 {
    font-size: 1.24rem/* 20px */;
    line-height: 1.75rem/* 28px */;
    font-weight:600;
    margin-top: 1.25rem;
    margin-bottom:0.75rem;
}
#summary h3 {
    text-transform:uppercase;
}
.iframe-container {
  overflow: hidden;
  /* 16:9 aspect ratio */
  padding-top: 56.25%;
  position: relative;
}

.iframe-container iframe {
   border: 0;
   height: 100%;
   left: 0;
   position: absolute;
   top: 0;
   width: 100%;
}
p a {
  color: orangered
}
</style>
